Configure Automation to build and publish Application (#159)
* Introduce a 'run' function to dry up fastlane

* Add private folder to gitignore :no_entry_sign:

* Set up profile configuration for the ios beta fastlane :ticket:

* Add missing icon size preventing ios to be published :clamp:

* Add apple generated icons :framed_picture:

* Add ios/release to gitignore and clear its content :package:

* Add src/modules/version.json to gitignore :ghost:

* Add ios icons for ipad :night_with_stars:

* Configure manifest and chaneg buildcode to have a release version :hammer_and_wrench:

* Start to draft a version to fetch version code from api :memo:

* Implement the fastlane action to fetch version_code :fishing_pole_and_fish:

* Attempt to inject VERSION_CODE as 'CFBundleVersion' :ticket:

* Introduce a run and run_npm_script step to improve Fastfile :gear:

* Clean up run_npm_script in Fastfile :dash:

* Improving the Fastfile and its actions :star2:

* Simplify custom fastlane action not to use magic var :level_slider:

* Now rely on the increment endpoint for version fetching :heavy_plus_sign:

* Add symbolic link for fastlane actions to reuse them in android :link:

* Add npm run update:version to postinstall step :gear:

* Some more tweaks to the fastlane configuration :wrench:

* Upgrade fastlane version :rocket:

* Tweak to the circle-ci config to preserve src/modules/version.json :shield:

* Configure Automation to build and publish Application fixes (#167)

* Restore build version to 1

* Use fastlane-plugin-yarn

* Share plugin across platform

* Explicit path for version.json

* Explicit package.json path

* Upgrade and manage dependencies for fastlane plugin

* Publication from circle ci (#169)

* Configure manifest and chaneg buildcode to have a release version :hammer_and_wrench:

* Start to draft a publish_ios job in circle ci :rocket:

* Start to configure a publish_android job :gear:

* Tweaks circle ci configuration :wrench:

* Bump detox to latest version as it breaks on circle :arrow_up:

* Update android lock file post detox10 bump :lock:

* Try workaround to have detox not crashing on ios install :boom:

* Add a way to circleci publish_android to retrieve service account :key:

* Try to tweak around the detox ios problem :man_shrugging:

* Rewrite two script in vanillajs not to use babel node :memo:

* Promote shelljs as a dependency for working --production install :shell:

* Try some hack to remove detox before install on ios publicatoni :wastebasket:

* Downgrade xcode macos version but bump yarn myself :gear:

* Remove old version code in android build.gradle :bug:

* Update two Gemfile.lock to have fixed fastlane-plugin-fetch_version_code :arrow_up:

* Add skip_waiting_for_build_processing option to testflight :wrench:

* Add NSMicrophoneUsageDescription to the Info.plist :policeman:

* Fix version in snapshot

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,6 +25,7 @@ jobs:
           root: ~/app
           paths:
             - node_modules
+            - src/modules/version.json
 
   linting:
     working_directory: ~/app
@@ -332,6 +333,60 @@ jobs:
             echo "Deploying on ${BRANCH_NAME}"
             ssh ${AWS_USER}@${AWS_DOMAIN} "mkdir -p /var/www/html/${BRANCH_NAME} -v"
             scp dist/* ${AWS_USER}@${AWS_DOMAIN}:/var/www/html/${BRANCH_NAME}/
+
+  publish_android:
+    working_directory: ~/app
+    docker:
+      - image: circleci/android:api-28-node
+    steps:
+      - checkout
+      - run:
+          name: Gems dependencies
+          command: cd android && bundle install
+
+      - run:
+          name: Npm dependencies
+          command: yarn
+
+      - run:
+          name: SDK licenses
+          # Keep "|| true" because yes command handles a 141 exit code
+          command: yes | sdkmanager "build-tools;28.0.3" "platforms;android-28" || true
+
+      - run:
+          name: Gradle dependencies
+          command: cd android && ./gradlew androidDependencies
+          environment:
+            ANDROID_HOME: /opt/android/sdk
+
+      - run:
+          name: Pull certificate and Service Account
+          command: |
+              yarn pull:certificate:android
+              echo "${ANDROID_SERVICE_ACCOUNT}" > android/service-account.json
+
+      - run:
+          name: Build and Publish
+          command: cd android && bundle exec fastlane beta
+
+  publish_ios:
+    macos:
+      xcode: "10.1.0"
+    working_directory: ~/app
+    steps:
+      - checkout
+      - run:
+          name: Gems dependencies
+          command: (cd ios && bundle install)
+      - run:
+          name: Setup dependencies
+          command: |
+            npm install -g yarn
+            yarn remove detox
+            yarn
+      - run:
+          name: Build and Publish
+          command: cd ios && bundle exec fastlane beta
 
 workflows:
   version: 2
